import { auth } from "@/auth";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-blue-500 p-6 mb-8 border-b-4 border-black shadow-[0_4px_0_0_rgba(0,0,0,1)] flex justify-between items-center">
          <h1 className="text-5xl font-bold text-white">GoGoals</h1>
          <div className="flex items-center">
            {session?.user ? (
              <Image
                src={session.user.image || "/default-avatar.png"}
                alt="User profile"
                width={40}
                height={40}
                className="w-10 h-10 rounded-full border-2 border-white"
              />
            ) : (
              <button className="bg-white text-blue-500 px-4 py-2 rounded-full font-semibold">
                Sign In
              </button>
            )}
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
